### PR TITLE
Portuguese translation of the FAQs

### LINKED ISSUE #81: Add Portuguese translation
It would be nice to have a Portuguese translation of the app. :portugal: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

Android Studio Translation Editor

# TODOs

- [x] Add new translations in `Umweltzone/src/main/res/values-pt/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Do not modify, commit files outside of the `-pt` folder.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
- [x] Add new translations in `Umweltzone/src/main/res/values-pt/ckchangelog.xml`.
- [x] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw-pt/faqs.json`
  - The English and German files can be found in the `Umweltzone/src/main/res/raw/` and `Umweltzone/src/main/res/raw-de/` folders.
  faqs

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

### PR DESCRIPTION
**Pull request by romeroclaudino**
# Translation to Portuguese of the faqs.json file.

Resolves #81

*This contribution aims to make this application accessible for Portuguese speakers.*

## List of changes proposed in this PR (pull-request)

* *Creation of the **Umweltzone/src/main/res/raw-pt/faqs.json** file, containing the Portuguese translation.*

### CODE REVIEW

**Comment by romeroclaudino** [comment]
There you go, @johnjohndoe.

I only have a doubt to clarify with you...

In the item with the position number 11, the answer says that the penalty is not applied in Flensburg, right?
I wasn't completely sure when I read it.

**Comment by johnjohndoe** [comment]
> In the item with the position number 11, the answer says that the penalty is not applied in Flensburg, right?
> I wasn't completely sure when I read it.

In the city of Flensburg there is the [Federal Motor Transport Authority](https://en.wikipedia.org/wiki/Point_system_(driving)#Germany) which operates a Germany wide **point system** for traffic misbehavior. In case of the 11th question there is no point applied, "just" some Euros to pay.

**Comment by romeroclaudino** [comment]
Ohh okay
Now I get it. So it's actually a 80 Euro fine + some points in the driver's license, right?!
But only in Flensburg the points are not applied...

I had gotten something else... I know when somebody says: "There's no point" it actually means "It doesn't make sense". So I've gotten confused with that.

**Comment by johnjohndoe** [comment]
Not exactly. You can get points in Flensburg in some cases. In this case you do not get any point. That is what the answer says.

**Comment by romeroclaudino** [comment]
Oh yeaa
Sure! For this specific case...

I just updated the file.

**Review by johnjohndoe — APPROVED** [review]
Muito obrigado @romeroclaudino. I just added a single space but for the rest I found no issues. I appreciate (once again) your effort for translating the app!

**Pull request merged**
